const resolvedPromise = () => {
    return new Promise((resolve, reject) => {
        // set a timeout of 500ms, after which the promise will be resolved with a message "Success"
        setTimeout(() => {
            resolve("Success");
        }, 500);
    });
};

const rejectedPromise = () => {
    return new Promise((resolve, reject) => {
        // set a timeout of 500ms, after which the promise will be rejected with an error message "Error"
        setTimeout(() => {
            reject(new Error("Error"));
        }, 500);
    });
};

// call both promises separately and handle the resolved and rejected results
resolvedPromise().then(console.log).catch(console.log);
rejectedPromise().then(console.log).catch(console.log);

